name = "gps-tracker-worker"
main = "./dist/index.mjs"
compatibility_date = "2022-09-08"

[build]
command = "npm install && npm test && npm run build"

[durable_objects]
bindings = [{name = "TRACKER", class_name = "Tracker"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Tracker"]
